name: Auto-actualiza lista M3U

on:
  workflow_dispatch:
  schedule:
    # Ejecuta cada 6 horas (ajusta a tu gusto)
    - cron: "0 */6 * * *"

permissions:
  contents: write

jobs:
  update-m3u:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scraper/requirements.txt

      - name: Run scraper
        run: |
          python scraper/update_m3u.py

      - name: Commit & push changes (if any)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: actualiza lista.m3u automáticamente"
          file_pattern: "lista.m3u"
